name: Run Unit Tests
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "cpp"
          queries: "+security-and-quality"
      - name: Run Unit Tests
        uses: ./tests/CI/run-unit-test
      - name: Uploading coverage result
        uses: actions/upload-artifact@v2
        with:
          name: gcovr coverage result
          path: tests/coverage.html
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1
